#!/bin/bash
#SBATCH -J job.ph             # Job name
#SBATCH -N 2                  # Total # of nodes
#SBATCH --ntasks-per-node 56
#SBATCH -t 01:00:00           # Run time (hh:mm:ss)
#SBATCH -A EPSchool2022
#SBATCH -p small
#SBATCH --reservation=EPSchoolDay4

# Launch MPI code...
export PATHQE=/work2/06868/giustino/EP-SCHOOL/q-e

##ibrun $PATHQE/bin/pw.x -nk 112 -in scf.in > scf.out
##ibrun $PATHQE/bin/ph.x -nk 112 -in ph.in > ph.out
##ibrun $PATHQE/bin/pw.x -nk 112 -in nscf.in > nscf.out
ibrun -np 112 $PATHQE/bin/epw.x -npool 112 -in epw3.in > epw3.out

exit
