#!/bin/bash
#SBATCH -J job.ph             # Job name
#SBATCH -N 2                  # Total # of nodes
#SBATCH --ntasks-per-node 56
#SBATCH -t 01:00:00           # Run time (hh:mm:ss)
#SBATCH -A EPSchool2022
#SBATCH -p small
#SBATCH --reservation=EPSchoolDay5

# Launch MPI code...
export PATHQE=/work2/06868/giustino/EP-SCHOOL/q-e

##ibrun $PATHQE/bin/pw.x -nk 112 -in si.scf.in > si.scf.out
##ibrun $PATHQE/bin/ph.x -nk 112 -in si.ph.in > si.ph.out
##ibrun $PATHQE/bin/q2r.x -nk 1 -in q2r.in > q2r.out
##ibrun -np 1 $PATHQE/bin/matdyn.x -npool 1 -in matdyn.in > matdyn.out
##ibrun -np 64 $PATHQE/bin/ZG.x -npool 64 -in ZG_333.in > ZG_333.out
##ibrun -np 64 $PATHQE/bin/pw.x -npool 64 -in equil-scf_333.in > equil-scf_333.out
ibrun -np 56 $PATHQE/bin/pw.x -nk 8 -i ZG-scf_333_0.00K.in > ZG-scf_333_0.00K.out

exit
